### PR TITLE
Db Connection implementation: handle_execute + prepare + bind

### PR DESCRIPTION
**Pull request by dmitriid**
This builds on #2.

Relevant commits: 

- 1242c1e `handle_execute` implementation. Includes prepare and bind
- 404ce4d and 99f4f09 are minor code fixes to handle this

Note: everything is as barebones as possible, just to check that everything is working. So, no funny majick around bind, for example :) See inline comments for TODOs

### CODE REVIEW

**Comment by warmwaffles** [comment]
@dmitriid could you do a rebase or update your branch based on what is merged in?

**Comment by dmitriid** [comment]
@warmwaffles Did a quick rebase.

I've seen your commits into #1 but haven't looked at them in detail 👍 It looks like we're doing more-or-less the same thing. You're just doing it faster :D

**Comment by warmwaffles** [comment]
@dmitriid I've just been cobbling together stuff and refactoring. There is just so much extra cruft in all of this.

I'm going to go the route you are taking and make these smaller chunks.

**Comment by dmitriid** [comment]
@warmwaffles That's so true. This was the case when I tried to go in guns a-blazing in https://github.com/dmitriid/sqelect/tree/update-attempt-the-first

It does become weird when you go into the actual ecto adapter. Suddenly you feel like you need 100 things at once (encoding, decoding, oh my). But may be taking things chunk by chunk will work.

**Comment by warmwaffles** [comment]
> It does become weird when you go into the actual ecto adapter. Suddenly you feel like you need 100 things at once (encoding, decoding, oh my). But may be taking things chunk by chunk will work.

Yea that was really confusing. I am trying to figure out parts we can lift out and test appropriately. 

Though as I just worked through trying to make tests pass I was able to decipher what the intentions were.

**Review by warmwaffles — APPROVED** [review]

**Pull request merged**
