### PR TITLE
Adds RETURNING support

### LINKED ISSUE #76: Add support for RETURNING clause
Now that we have 3.35.0 we can support this.

see #75

### PR DESCRIPTION
**Pull request by warmwaffles**
closes #76

### CODE REVIEW

**Comment by warmwaffles** [comment]
@kevinlang this just generates the SQL necessary to support returning.

Is there an integration in ecto_sql that we can pull in for this?

**Comment by warmwaffles** [comment]
Found it, it's the `returning` tag being excluded.

**Comment by kevinlang** [comment]
`function nil.encode/1 is undefined` is due to the `:json_library` thing. 

I think what we will need to do, to get rid of the warning, is adopt the pattern in other adapters which do:
```
 Application.get_env(:postgrex, :json_library, Jason)
 ```
 Everytime they access the json library to avoid our needing to set it in test setup

**Comment by warmwaffles** [comment]
Yea I feel ya there. Stupid warning. I'll revert that.

**Comment by warmwaffles** [comment]
@kevinlang I have 1 test failing in the integration test suite. This also flips back over to the provided repo integration test

**Comment by warmwaffles** [comment]
I rebased it off of main. I have to head out for the evening and if you find a fix go ahead and push it into here and merge away.

**Comment by kevinlang** [comment]
Nice work! For #80 , I'm not sure if there is a clean solution. I was looking through and assumed that Postgrex and others roguely tacked on `RETURNING` clauses under the hood to get insert ids, but that doesn't seem to be the case. I can't find any solution actually to the `:on_conflict_ignore` thing, am I missing something?

**Comment by kevinlang** [comment]
The fix was just a matter of removing a bunch of our custom `insert` "override" code. 

Now the ecto layer no longer has any more need for the last insert id. We may want to add some way to avoid making the `last_insert_id` call when using the lower-level driver with ecto, to eek out some extra perf.

**Pull request merged**
